server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: album-api

  datasource:
    url: ${JDBC_POSTGRES_URL:jdbc:postgresql://localhost:5432/ivanbatistamoreno206660db}
    driver-class-name: org.postgresql.Driver
    username: ${JDBC_POSTGRES_USER:userdb}
    password: ${JDBC_POSTGRES_PASSWORD:userdb}

  jpa:
    properties:
      hibernate:
        show_sql: ${HIBERNATE_SHOW_SQL:false}
        format_sql: ${HIBERNATE_FORMAT_SQL:false}

  actuator:
    endpoint:
      health:
        probes:
          enabled: true
    health:
      livenessstate:
        enabled: true
      readinessstate:
        enabled: true

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

springdoc:
  show-actuator: true
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:false}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:false}
    path: /swagger-ui.html
    operationsSorter: method

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:ROOTNAME}
  secretKey: ${MINIO_SECRET_KEY:ROOTPASSWORD}
  bucketName: ${MINIO_BUCKET_NAME:image-bucket}

regional:
  api:
    base-url: ${REGIONAL_API_URL:https://integrador-argus-api.geia.vip}
